baseURL = "https://hamzeiehsan.github.io/"
languageCode = "en-us"
title = 'Ehsan Hamzei | Personal Website'
theme = 'stack'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5

# Markdown renderer configuration
[goldmark.renderer]
unsafe = false

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"
