baseURL = "https://hamzeiehsan.github.io/"
languageCode = "en-us"
title = 'Ehsan Hamzei | Personal Website'
theme = 'stack'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 5