name: github pages

on:
  push:
    branches:
      - main
  pull_request:

# Silences the deprecation warnings by forcing the runner to run JS actions on Node 24
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Updated to v5 (Supports Node 24)
        with:
          submodules: true
          fetch-depth: 0

      - name: Hugo setup
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public